---
- name: Deploy to Kubernetes using existing Docker image
  hosts: worker
  become: yes
  vars:
    docker_image_name: "mrbadd/abc-retail-app"
    docker_image_tag: "{{ build_number }}"
    kubeconfig_path: "/var/lib/jenkins/.kube/config"
    namespace: "abc-technologies"

  tasks:
    - name: Ensure namespace exists
      kubernetes.core.k8s:
        kubeconfig: "{{ kubeconfig_path }}"
        state: present
        definition:
          apiVersion: v1
          kind: Namespace
          metadata:
            name: "{{ namespace }}"

    - name: Deploy Kubernetes Deployment
      kubernetes.core.k8s:
        kubeconfig: "{{ kubeconfig_path }}"
        state: present
        definition:
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: abc-retail-deployment
            namespace: "{{ namespace }}"
            labels:
              app: abc-retail
          spec:
            replicas: 1
            selector:
              matchLabels:
                app: abc-retail
            template:
              metadata:
                labels:
                  app: abc-retail
              spec:
                containers:
                  - name: abc-retail-container
                    image: "{{ docker_image_name }}:{{ docker_image_tag }}"
                    ports:
                      - containerPort: 8080

    - name: Deploy Kubernetes Service
      kubernetes.core.k8s:
        kubeconfig: "{{ kubeconfig_path }}"
        state: present
        definition:
          apiVersion: v1
          kind: Service
          metadata:
            name: abc-retail-service
            namespace: "{{ namespace }}"
          spec:
            selector:
              app: abc-retail
            ports:
              - protocol: TCP
                port: 8080
                targetPort: 8080
            type: NodePort

